GET http://localhost:5000/users

###
GET http://localhost:5000/users/1

###
POST http://localhost:5000/users
Content-Type: application/json

{
  "name" : "andi",
  "email" : "andiseo50@gmail.com",
  "contact" : "081344405159",
  "username" : "itsme_andiseo",
  "password" : "seyo@8323"
}

###
PATCH  http://localhost:5000/users/1
Content-Type: application/json

{
  "email" : "andiseo50@gmail.com",
  "contact" : "081344405159",
  "username" : "itsme_andiseo",
  "password" : "seyo@8323003"
}